const $=selector=>document.querySelector(selector),grid=$('#grid'),log=$('#log'),t=(key,...args)=>window.sxI18n?.t(key,...args)??key;
let stream,context,node,inputGainNode,ofdmWorker,started=0,timer,wake,loading=false,ofdmPhase=false,fskLines=0,fskChars=0,rawBits='',guidePeak=0,guideAt=0;
let hudDone=0,hudTotal=0,receiveElapsed=0,receiveFinished=false,receiveError=false,crcNg=0,effectiveBps=0,stateErrorUntil=0;
let wireHeader=null,wireBlocks=new Map(),wireStoredSize=0,wireTotalBlocks=0,wireV3=false,fskBoundary=false;
let wireBlockBytes=32768,negotiatedBlocks=16;
let freshNegotiation=false;
let pendingLevel=null,levelFrame=0;
let negotiationMs=0,fskMs=0,ofdmMs=0,fskPhaseAt=0,ofdmPhaseAt=0,packetCrcErrors=0,fecRecovered=0,fskSumErrors=0,blockCrcErrors=0,fecFailures=0,transferAborted=false;
let lapTimes=[],lapLastAt=0,lapRecordedBlocks=0,lastRaceLap=-1,lapCutinTimer=0,goalTimer=0,goalArrivalTimer=0;
let startCutinTimer=0;
let receivedDataOffsets=new Set(),receivedDataBytes=0;
let crcNgRun=0;
function renderLapTimes(){const panel=$('#lap-times');if(!panel)return;panel.replaceChildren();const label=document.createElement('span');label.textContent='BLOCK LAP TIME';panel.append(label);if(!lapTimes.length){const empty=document.createElement('strong');empty.textContent='—';panel.append(empty);return}for(const lap of lapTimes){const item=document.createElement('strong');item.textContent=`LAP ${lap.number} / BLOCK ${String(lap.number).padStart(2,'0')}  ${lap.lap.toFixed(2)} s  TOTAL ${lap.total.toFixed(2)} s`;panel.append(item)}}
function showLapCutin(lap){const cutin=$('#lap-cutin');if(!cutin)return;cutin.innerHTML=`<small>LAP ${String(lap.number).padStart(2,'0')} COMPLETE</small><strong>${lap.lap.toFixed(2)} s</strong>`;cutin.classList.remove('show');void cutin.offsetWidth;cutin.classList.add('show');clearTimeout(lapCutinTimer);lapCutinTimer=setTimeout(()=>cutin.classList.remove('show'),1800)}
function showStartCutin(value){const cutin=$('#start-cutin');if(!cutin)return;cutin.textContent=value;cutin.classList.remove('show','go');if(value==='GO!')cutin.classList.add('go');void cutin.offsetWidth;cutin.classList.add('show');clearTimeout(startCutinTimer);startCutinTimer=setTimeout(()=>cutin.classList.remove('show','go'),value==='GO!'?900:480)}
function recordBlockLaps(completed){if(!started)return;while(lapRecordedBlocks<completed){const total=(performance.now()-started)/1000,to=lapRecordedBlocks+1,lap={number:to,lap:total-lapLastAt,total};lapTimes.push(lap);lapRecordedBlocks=to;lapLastAt=total;showLapCutin(lap)}renderLapTimes()}
function renderResultLaps(){const list=$('#result-laps');if(!list)return;list.replaceChildren();for(const [index,lap] of lapTimes.entries()){const item=document.createElement('li');item.style.setProperty('--result-index',index);item.innerHTML=`<b>LAP ${String(lap.number).padStart(2,'0')}</b><strong>${lap.lap.toFixed(2)} s</strong><small>TOTAL ${lap.total.toFixed(2)} s</small>`;list.append(item)}}
function clearGoalCelebration(){clearTimeout(goalTimer);goalTimer=0;clearTimeout(goalArrivalTimer);goalArrivalTimer=0;const overlay=$('#goal-overlay');if(overlay){overlay.hidden=true;overlay.classList.remove('show')}const confetti=$('#confetti');if(confetti)confetti.replaceChildren()}
function showGoalCelebration(){clearGoalCelebration();renderResultLaps();const overlay=$('#goal-overlay'),confetti=$('#confetti');if(!overlay||!confetti){const dialog=$('#complete-dialog');if(dialog&&!dialog.open)dialog.showModal();return}for(let index=0;index<84;index++){const piece=document.createElement('i');piece.style.setProperty('--x',`${(index*47)%101}vw`);piece.style.setProperty('--drift',`${((index*29)%41)-20}vw`);piece.style.setProperty('--delay',`${(index%14)*.07}s`);piece.style.setProperty('--fall',`${2.2+(index%9)*.18}s`);piece.style.setProperty('--spin',`${360+(index%7)*180}deg`);piece.style.setProperty('--color',['#ff2638','#ff8a18','#ffd52a','#fff','#d90032'][index%5]);confetti.append(piece)}overlay.hidden=false;void overlay.offsetWidth;overlay.classList.add('show');goalTimer=setTimeout(()=>{overlay.classList.remove('show');overlay.hidden=true;const dialog=$('#complete-dialog');if(dialog&&!dialog.open)dialog.showModal()},5000)}
function showGoalAfterArrival(){const car=$('#course-car');if(!car){showGoalCelebration();return}moveCourseCar(1,1,false);clearTimeout(goalArrivalTimer);goalArrivalTimer=setTimeout(()=>{goalArrivalTimer=0;showGoalCelebration()},180)}
function resetTransferStats(){negotiationMs=fskMs=ofdmMs=0;fskPhaseAt=ofdmPhaseAt=0;packetCrcErrors=fecRecovered=fskSumErrors=blockCrcErrors=fecFailures=crcNgRun=0;transferAborted=false;lapTimes=[];lapLastAt=lapRecordedBlocks=0;lastRaceLap=-1;renderLapTimes();const stats=$('#transfer-stats');if(stats){stats.hidden=true;stats.textContent=''}}
function startRace(agoMs=0,source='start signal'){if(started)return;started=performance.now()-Math.max(0,agoMs);ofdmPhaseAt=started;receiveElapsed=0;lapLastAt=0;setCourseCarRunning();showStartCutin('GO!');$('#elapsed').textContent='0.00 s';$('#state').textContent=t('goSearch');$('#signal-progress').textContent='START';write(`GO — TIMER START (${source})`)}
function showTransferStats(){const totalMs=receiveElapsed*1000,ofdmTime=ofdmMs||totalMs,otherMs=Math.max(0,totalMs-ofdmTime),stats=$('#transfer-stats'),rate=totalMs>0?wireStoredSize*8/(totalMs/1000):0;if(!stats)return;stats.hidden=false;stats.innerHTML=`<strong>受信統計</strong><span><small>合計</small><b>${fmtMs(totalMs)}</b></span><span><small>OFDM</small><b>${fmtMs(ofdmTime)}</b></span><span><small>その他</small><b>${fmtMs(otherMs)}</b></span><span><small>実データ</small><b>${wireStoredSize.toLocaleString('ja-JP')} bytes</b></span><span><small>実効レート</small><b>${Math.round(rate).toLocaleString('ja-JP')} bps</b></span><span><small>Packet CRCエラー</small><b>${packetCrcErrors}</b></span><span><small>ブロックCRCエラー</small><b>${blockCrcErrors}</b></span><span><small>FEC訂正</small><b>${fecRecovered} shards</b></span><span><small>FEC訂正不能</small><b>${fecFailures}</b></span>`;write(`STATS TOTAL=${fmtMs(totalMs)} OFDM=${fmtMs(ofdmTime)} OTHER=${fmtMs(otherMs)} RATE=${Math.round(rate)}bps PKT_CRC_NG=${packetCrcErrors} BLOCK_CRC_NG=${blockCrcErrors} FEC=${fecRecovered} FEC_FAILED=${fecFailures}`)}
function fmtMs(ms){return `${(Math.max(0,ms)/1000).toFixed(2)} s`}function abortTransfer(reason){receiveElapsed=started?(performance.now()-started)/1000:receiveElapsed;transferAborted=true;ofdmWorker?.postMessage({type:'disarm'});setWireCursor(null);setStar('err');$('#state').textContent=reason;$('#decode-badge').textContent='ERROR';hudError();showTransferStats()}
/* Effective rate is sampled only when a complete block passes stored CRC32. */
function updateHud(){if(receiveError)return;if(!receiveFinished&&started)receiveElapsed=(performance.now()-started)/1000;const totalBytes=wireStoredSize||wireTotalBlocks*wireBlockBytes,doneBytes=receiveFinished?totalBytes:Math.min(receivedDataBytes,totalBytes),pct=totalBytes?100*doneBytes/totalBytes:0,totalBlocks=wireTotalBlocks||Math.ceil(totalBytes/wireBlockBytes),doneBlocks=receiveFinished?totalBlocks:Math.min(totalBlocks,Math.floor(doneBytes/wireBlockBytes)),progress=$('#hud-progress'),rate=$('#hud-rate'),eta=$('#eta'),totalBits=totalBytes*8,locale=window.sxI18n?.locale||'ja';if(progress)progress.textContent=`${pct.toFixed(2)}% (${doneBlocks}/${totalBlocks||'—'}) ${receiveElapsed.toFixed(2)} s`;if(rate)rate.textContent=`${t('effective')} ${Math.round(effectiveBps).toLocaleString(locale)} bps`;if(eta)eta.textContent=effectiveBps>0&&totalBits?`${(totalBits/effectiveBps).toFixed(2)} s`:'—'}
/* On a terminal error, paint the final numbers, turn the HUD red and freeze it. */
function hudError(){receiveFinished=true;updateHud();receiveError=true;const h=$('#hud');if(h)h.classList.add('err')}
function resetHud(){hudDone=hudTotal=0;receiveElapsed=0;receiveFinished=false;receiveError=false;crcNg=0;effectiveBps=0;receivedDataOffsets.clear();receivedDataBytes=0;resetScopePeaks();const progress=$('#hud-progress'),rate=$('#hud-rate'),eta=$('#eta'),h=$('#hud');if(progress)progress.textContent='0.00% (0/—) 0.00 s';if(rate)rate.textContent=`${t('effective')} 0 bps`;if(eta)eta.textContent='—';if(h)h.classList.remove('err')}
const COURSE_PATH='M 130 52 H 785 Q 925 52 925 155 V 192 L 805 340 H 325 Q 245 340 245 272 V 218 Q 245 158 315 158 H 602 Q 675 158 675 216 V 238 Q 675 278 620 278 H 430 L 350 368 H 155 Q 55 368 55 270 V 150 Q 55 52 130 52 Z';
function blockCells(){return [...grid.querySelectorAll(':scope>i')]}
function coursePoint(phase){const path=$('#course-path'),p=Math.max(0,Math.min(1,phase));if(!path)return{x:50,y:50,angle:0};const length=path.getTotalLength(),at=p*length,point=path.getPointAtLength(at),next=path.getPointAtLength(Math.min(length,at+2));return{x:point.x/10,y:point.y/4.2,angle:Math.atan2(next.y-point.y,next.x-point.x)*180/Math.PI}}
function buildGrid(blockBytes,blocks){grid.replaceChildren();const kib=blockBytes/1024,svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),track=document.createElementNS(svg.namespaceURI,'path'),center=document.createElementNS(svg.namespaceURI,'path'),progress=document.createElementNS(svg.namespaceURI,'path'),runner=document.createElement('b'),cutin=document.createElement('div');svg.setAttribute('viewBox','0 0 1000 420');svg.setAttribute('aria-hidden','true');svg.classList.add('course-map');track.id='course-path';track.setAttribute('d',COURSE_PATH);svg.append(track);grid.append(svg);runner.id='course-car';runner.setAttribute('aria-hidden','true');cutin.id='lap-cutin';cutin.setAttribute('aria-live','polite');for(let i=0;i<blocks;i++){const sector=document.createElementNS(svg.namespaceURI,'path'),cell=document.createElement('i'),point=coursePoint(i/blocks);sector.setAttribute('d',COURSE_PATH);sector.setAttribute('pathLength',String(blocks));sector.setAttribute('stroke-dasharray',`.86 ${Math.max(.14,blocks-.86)}`);sector.setAttribute('stroke-dashoffset',String(-i));sector.dataset.block=String(i);sector.classList.add('course-sector','missing');svg.append(sector);cell.className='missing';cell.title=`BLOCK ${i+1}${i+1===blocks?' / GOAL':''} / ${i*kib}-${(i+1)*kib} KiB`;cell.setAttribute('aria-label',`Block ${i+1}${i+1===blocks?' / Goal':''}`);cell.style.setProperty('--course-x',`${point.x}%`);cell.style.setProperty('--course-y',`${point.y}%`);cell.style.setProperty('--course-angle',`${point.angle}deg`);grid.append(cell)}center.id='course-center';center.setAttribute('d',COURSE_PATH);svg.append(center);progress.id='course-progress';progress.setAttribute('d',COURSE_PATH);svg.append(progress);grid.append(runner,cutin);moveCourseCar(0,1);setCourseCarIdle();const spec=$('#block-spec');if(spec)spec.textContent=`${Number.isInteger(kib)?kib:kib.toFixed(2)} KiB × ${blocks}`;$('#summary').textContent=t('summary',0,0,blocks)}
function moveCourseCar(packet,total,paint=true){const car=$('#course-car');if(!car)return;let finish=$('#finish-line');if(!finish){finish=document.createElement('span');finish.id='finish-line';finish.setAttribute('aria-label','LAP計測ライン');grid.append(finish)}const linePhase=.025,startPoint=coursePoint(linePhase),laps=Math.max(1,wireTotalBlocks||blockCells().length),overall=Math.max(0,Math.min(1,(packet||0)/Math.max(1,total))),lapProgress=overall*laps,lap=Math.min(laps-1,Math.floor(lapProgress)),phase=overall>=1?linePhase:(linePhase+lapProgress)%1,point=coursePoint(phase),progress=$('#course-progress'),path=$('#course-path');finish.style.setProperty('--finish-x',`${startPoint.x}%`);finish.style.setProperty('--finish-y',`${startPoint.y}%`);finish.style.setProperty('--finish-angle',`${startPoint.angle}deg`);if(paint){recordBlockLaps(Math.min(laps,Math.floor(lapProgress)));lastRaceLap=lap}grid.classList.toggle('final-lap',lap===laps-1);car.style.setProperty('--car-x',`${point.x}%`);car.style.setProperty('--car-y',`${point.y}%`);car.style.setProperty('--car-angle',`${point.angle}deg`);car.setAttribute('aria-label',`F1カー LAP ${lap+1} / ${laps}`);if(paint&&progress&&path){const length=path.getTotalLength(),progressPhase=overall<=0?0:overall>=1?1:phase;progress.style.strokeDasharray=String(length);progress.style.strokeDashoffset=String(length*(1-progressPhase))}car.classList.add('running')}
function setCourseCarIdle(){const car=$('#course-car');if(!car)return;car.classList.remove('running','crc-spin','crash');car.classList.add('idle')}
function setCourseCarRunning(){const car=$('#course-car');if(!car)return;car.classList.remove('idle');car.classList.add('running')}
buildGrid(wireBlockBytes,negotiatedBlocks);
function errorReason(message){let match;if((match=message.match(/^\?OFDM PKT (\d+) .*CRC ERROR/)))return `エラー: OFDMパケットCRC不一致 #${match[1]}（FEC訂正待ち）`;if((match=message.match(/^\?OFDM FEC RECOVERY FAILED G(\d+) MISSING (\d+)/)))return `エラー: FEC訂正不能 G${match[1]}（欠損${match[2]}）`;if((match=message.match(/^\?V\d+ BLOCK\/SEQ (\d+) CRC32 ERROR/)))return `エラー: ブロックCRC不一致 SEQ ${match[1]}`;if(/FSK HEADER SUM ERROR/.test(message))return 'エラー: FSKヘッダSUM不一致';if(/FSK HEADER VERSION ERROR/.test(message))return 'エラー: FSKヘッダVERSION不正';if((match=message.match(/FSK SEQ (\d+) ERROR/)))return `エラー: FSK SEQ不正 ${match[1]}`;if(/FRAMING ERROR/.test(message))return 'エラー: FSKフレーミング不一致（再同期中）';if(/INCOMPLETE/.test(message))return 'エラー: ブロック受信未完了';return message.startsWith('ERROR')?`エラー: ${message.slice(5).trim()}`:null}
function write(message){const now=new Date(),stamp=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}.${String(now.getMilliseconds()).padStart(3,'0')}`;const line=document.createElement('div'),reason=errorReason(message);line.textContent=`[${stamp}] ${message}`;if(/^(\?|ERROR)/.test(message))line.className='err';if(reason){$('#state').textContent=reason;stateErrorUntil=performance.now()+5000}log.append(line);log.scrollTop=log.scrollHeight}
const DEVICE_LABEL_KEY='ps1sx.audioInputLabel';
const scopePeak={l:0,r:0};
function resetScopePeaks(){scopePeak.l=scopePeak.r=0}
async function devices(){const all=await navigator.mediaDevices.enumerateDevices(),current=$('#device').value,saved=localStorage.getItem(DEVICE_LABEL_KEY);$('#device').innerHTML=`<option value="">${t('defaultInput')}</option>`;for(const d of all.filter(item=>item.kind==='audioinput')){const option=document.createElement('option');option.value=d.deviceId;option.textContent=d.label||t('audioInput',$('#device').length);$('#device').append(option)}if(current&&[...$('#device').options].some(option=>option.value===current))$('#device').value=current;else if(saved){const match=[...$('#device').options].find(option=>option.textContent===saved);if(match)$('#device').value=match.value}}
function draw(data){const canvas=$('#scope'),pen=canvas.getContext('2d'),w=canvas.width,h=canvas.height,amp=h*.23,displayGain=1.6;pen.fillStyle='#030817';pen.fillRect(0,0,w,h);for(const [channel,samples,color,base,currentPeak,labelY] of [['l',data.left,'#50d8ff',h*.27,data.peakL,13],['r',data.right,'#ff3f9b',h*.73,data.peakR,h*.5+13]]){scopePeak[channel]=Math.max(scopePeak[channel],Math.abs(currentPeak||0));const heldPeak=scopePeak[channel];if(heldPeak){const pk=Math.min(heldPeak*displayGain,1)*amp;pen.strokeStyle='#f8d548';pen.lineWidth=1;pen.setLineDash([5,4]);pen.beginPath();pen.moveTo(0,base-pk);pen.lineTo(w,base-pk);pen.moveTo(0,base+pk);pen.lineTo(w,base+pk);pen.stroke();pen.setLineDash([]);pen.fillStyle='#f8d548';pen.font='11px ui-monospace,monospace';pen.fillText(`max ${db(heldPeak).toFixed(1)} dBFS`,6,labelY)}let phase=0;for(let i=0;i+1<samples.length;i++){const a=samples[i],b=samples[i+1];if(a<=0&&b>0){phase=i+(-a/(b-a));break}}pen.strokeStyle=color;pen.lineWidth=2;pen.beginPath();for(let index=0;index<samples.length;index++){const at=(phase+index)%samples.length,i0=Math.floor(at),frac=at-i0,i1=(i0+1)%samples.length,value=samples[i0]*(1-frac)+samples[i1]*frac,x=index*w/(samples.length-1),shown=Math.max(-1,Math.min(1,value*displayGain)),y=base-shown*amp;index?pen.lineTo(x,y):pen.moveTo(x,y)}pen.stroke()}}
function setStar(cls){const a=$('#activity');if(a)a.className=cls||''}
function fskStat(text,color){const el=$('#fsk-status');if(el){el.textContent=text;el.style.color=color||''}}
function setToggle(running){const b=$('#toggle');if(!b)return;b.textContent=t(running?'stop':'start');b.classList.toggle('running',!!running)}
function applyAnalyzerSetting(){const enabled=$('#analyzer-enabled')?.checked!==false;node?.port.postMessage({type:'analyzer-enabled',enabled});$('.telemetry')?.classList.toggle('analyzer-off',!enabled);localStorage.setItem('ps1sx.analyzer',enabled?'1':'0')}
function applyInputGain(){const dbValue=Number($('#input-gain')?.value||0),gain=Math.pow(10,dbValue/20);if(inputGainNode)inputGainNode.gain.setTargetAtTime(gain,context.currentTime,.01);const output=$('#input-gain-value');if(output)output.textContent=`${dbValue>=0?'+':''}${dbValue.toFixed(1)} dB`;localStorage.setItem('ps1sx.inputGainDb',String(dbValue))}
function setPct(text){$('#percent').textContent=text}
function showBlockHeader(message,ok=true){const el=$('#block-header');if(!el)return;el.className=`block-header ${ok?'good':'bad'}`;if(ok)el.textContent=`FSK HEADER: VER ${message.version||3}  SEQ ${String(message.sequence).padStart(3,'0')}  CRC32 ${message.crc.toString(16).toUpperCase().padStart(8,'0')}  SUM ${message.headerSum===undefined?'—':message.headerSum.toString(16).toUpperCase().padStart(2,'0')}  COPY ${message.headerAttempt||1}`;else el.textContent=`FSK HEADER: VER ${message.version}  SUM ERROR ${message.sum.toString(16).toUpperCase().padStart(2,'0')}  COPY ${message.attempt||'?'}`}
function showSequenceError(message){const el=$('#block-header');if(!el)return;el.className='block-header bad';el.textContent=`FSK HEADER: VER ${message.version}  SEQ ${String(message.sequence).padStart(3,'0')} ERROR`}
/* Legacy V3 captures used an FSK preamble. The current Burst V6 path starts
 * with the triangle signal and then runs continuous stereo OFDM. */
function resetReception(arm=true,preserveStart=false){ofdmPhase=false;if(arm)ofdmWorker?.postMessage({type:'arm'});clearBios();if(!preserveStart||!started)started=performance.now();const elapsed=(performance.now()-started)/1000;resetHud();if(preserveStart)receiveElapsed=elapsed;const cells=blockCells(),n=cells.length;for(const cell of cells){cell.className='missing';cell.style.removeProperty('--fill')}for(const sector of grid.querySelectorAll('.course-sector'))sector.setAttribute('class','course-sector missing');$('#ofdm-packets').textContent='0 / ?';$('#ofdm-crc').textContent='0 OK / 0 NG';$('#ofdm-recovered').textContent='0 bytes';$('#ofdm-drops').textContent='0';$('#ofdm-fec').textContent='16+6 / 待機';$('#ofdm-rate').textContent='0 kbps';$('#ofdm-quality').textContent='—';$('#ofdm-symbol').textContent='— / 4';setPct('0%');$('#summary').textContent=`完了 0 / エラー 0 / 未受信 ${n}`;write('RESET — new PS1SX transmission');}
function finishWireV3(){const data=new Uint8Array(wireStoredSize);for(let sequence=0;sequence<wireTotalBlocks;sequence++){const block=wireBlocks.get(sequence);if(!block)return;const offset=sequence*wireBlockBytes;data.set(block.subarray(0,Math.min(wireBlockBytes,data.length-offset)),offset)}const result=validateContainer(data.buffer);if(!result.ok){write(`?V3 CONTAINER ERROR ${result.error}`);hudError();return}const bios=reconstructBios(data.buffer);if(!bios.ok){write(`?BIOS REBUILD ERROR ${bios.error}`);hudError();return}receiveElapsed=started?(performance.now()-started)/1000:receiveElapsed;receiveFinished=true;updateHud();showTransferStats();offerBios(bios.image,bios.crc);setStar('ok');$('#state').textContent='BIOS受信完了';$('#decode-badge').textContent='COMPLETE';write(`V3 BIOS ${bios.image.length} bytes CRC32 ${bios.crc.toString(16).toUpperCase().padStart(8,'0')}`)}
function db(value){return 20*Math.log10(Math.max(value,1e-6))}
const hold={l:-60,r:-60};
function meter(channel,rms,peak){const peakDb=db(peak),bar=$(`#meter-${channel}`),pct=v=>Math.max(0,Math.min(100,(v+60)*100/60));bar.style.width=`${pct(peakDb)}%`;bar.classList.toggle('clip',peak>=.988);$(`#db-${channel}`).textContent=`${db(rms).toFixed(1)} / ${peakDb.toFixed(1)} dB`;hold[channel]=Math.max(peakDb,hold[channel]-0.8);const hm=$(`#hold-${channel}`);if(hm)hm.style.left=`${pct(hold[channel])}%`}
function levelGuide(peak){const guide=$('#level-guide');if(peak>=.988){guide.textContent='CLIP — レベルを下げる';guide.style.color='#ff6680'}else if(peak>.708){guide.textContent='HOT — 少し下げる';guide.style.color='#f8d548'}else if(peak<.06){guide.textContent='LOW — レベルを上げる';guide.style.color='#f8d548'}else if(peak<.25){guide.textContent='OK — もう少し上げても可';guide.style.color='#50d8ff'}else{guide.textContent='GOOD';guide.style.color='#3fe0a0'}}
function signed(value,digits=1){return `${value>=0?'+':''}${value.toFixed(digits)}`}
function telemetry(message){$('#snr').textContent=`${message.snr.toFixed(1)} dB`;$('#tone').textContent=`${message.tone} Hz`;$('#tone-ratio').textContent=`${signed(message.toneRatio)} dB`;$('#balance').textContent=`${signed(message.balance)} dB`;$('#peaks').textContent=`${db(message.peakL).toFixed(1)} / ${db(message.peakR).toFixed(1)} dBFS`;$('#rms-pair').textContent=`${db(message.rmsL).toFixed(1)} / ${db(message.rmsR).toFixed(1)} dBFS`;$('#crest').textContent=`${message.crestL.toFixed(1)} / ${message.crestR.toFixed(1)} dB`;$('#dc').textContent=`${signed(message.dcL,4)} / ${signed(message.dcR,4)}`;$('#correlation').textContent=message.correlation.toFixed(3);$('#clips').textContent=`${message.clips} samples`}
function renderLevel(){levelFrame=0;const message=pendingLevel;pendingLevel=null;if(!message)return;const active=loading&&message.rms>.012;$('#level').textContent=`${db(message.rms).toFixed(1)} dBFS`;meter('l',message.rmsL,message.peakL);meter('r',message.rmsR,message.peakR);guidePeak=Math.max(guidePeak,message.peakL,message.peakR);const now=performance.now();if(now-guideAt>2000){levelGuide(guidePeak);guidePeak=0;guideAt=now}if($('#analyzer-enabled').checked)telemetry(message);if(!ofdmPhase)setStar(active?'ofdm':'');$('#signal-progress').textContent=active?(started?'データあり':'スタート信号検出中'):'無信号';if(message.left)draw(message)}
function queueLevel(message){pendingLevel=message;if(!levelFrame)levelFrame=requestAnimationFrame(renderLevel)}
function crc32(data){let crc=0xffffffff;for(const value of data){crc^=value;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return (crc^0xffffffff)>>>0}
function fixedDeflateDecode(src,cap){const out=new Uint8Array(cap);let at=0,bits=0,count=0,pos=0,failed=false;const get=n=>{while(count<n){if(at>=src.length){failed=true;return 0}bits|=src[at++]<<count;count+=8}const v=bits&((1<<n)-1);bits>>>=n;count-=n;return v},rev=(v,n)=>{let r=0;while(n--){r=(r<<1)|(v&1);v>>>=1}return r},symbol=()=>{let code=0;for(let n=1;n<=9;n++){code=(code<<1)|get(1);if(failed)return-1;if(n===7&&code<=23)return 256+code;if(n===8){if(code>=48&&code<=191)return code-48;if(code>=192&&code<=199)return 280+code-192}if(n===9&&code>=400&&code<=511)return 144+code-400}return-1};if(get(1)!==1||get(2)!==1)return out.subarray(0,0);const lb=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258],le=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],db=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],de=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];for(;;){const s=symbol();if(s<0)return out.subarray(0,0);if(s<256){if(pos>=cap)return out.subarray(0,0);out[pos++]=s;continue}if(s===256)return out.subarray(0,pos);if(s>285)return out.subarray(0,0);const li=s-257,len=lb[li]+get(le[li]),dc=rev(get(5),5);if(failed||dc>=30)return out.subarray(0,0);const distance=db[dc]+get(de[dc]);if(failed||distance>pos||pos+len>cap)return out.subarray(0,0);for(let i=0;i<len;i++){out[pos]=out[pos-distance];pos++}}}
function lzssDecode(src,cap){const dst=new Uint8Array(cap);let inp=0,out=0;while(inp<src.length){const flags=src[inp++];for(let bit=0;bit<8&&inp<src.length;bit++){if(flags&(1<<bit)){if(out>=cap)return dst.subarray(0,out);dst[out++]=src[inp++]}else{if(inp+2>src.length)return dst.subarray(0,out);const lo=src[inp++],hi=src[inp++],distance=1+lo+((hi&15)<<8),length=3+(hi>>4);if(distance>out||out+length>cap)return dst.subarray(0,out);for(let i=0;i<length;i++){dst[out]=dst[out-distance];out++}}}}return dst.subarray(0,out)}
function reconstructBios(buffer){const data=new Uint8Array(buffer),view=new DataView(buffer);if(data.length<28||view.getUint32(0,true)!==0x58533150)return{ok:false,error:'SXヘッダ不正'};const version=view.getUint16(4,true);if(version===2)return{ok:false,error:'SX V2 LZMA2は受信側未実装（PENDING）'};const originalSize=view.getUint32(8,true),imageCrc=view.getUint32(16,true)>>>0,blockSize=view.getUint16(20,true),blocks=view.getUint16(22,true);const image=new Uint8Array(originalSize);let at=view.getUint16(6,true);for(let i=0;i<blocks;i++){if(at+16>data.length)return{ok:false,error:`block ${i} header`};const index=view.getUint16(at,true),codec=data[at+2],origSize=view.getUint16(at+4,true),storedSize=view.getUint16(at+6,true),origCrc=view.getUint32(at+8,true)>>>0;at+=16;if(at+storedSize>data.length)return{ok:false,error:`block ${i} payload`};const payload=data.subarray(at,at+storedSize);at+=storedSize;const blk=codec===1?lzssDecode(payload,origSize):codec===2?fixedDeflateDecode(payload,origSize):codec===0?payload:new Uint8Array();if(blk.length<origSize||crc32(blk.subarray(0,origSize))!==origCrc)return{ok:false,error:`block ${index} CRC`};image.set(blk.subarray(0,origSize),index*blockSize)}if(crc32(image)!==imageCrc)return{ok:false,error:'イメージCRC不一致'};return{ok:true,image,crc:imageCrc}}
let biosUrl=null,biosOffered=false;
function clearBios(){biosOffered=false;clearGoalCelebration();const dialog=$('#complete-dialog');if(dialog?.open)dialog.close();if(biosUrl){URL.revokeObjectURL(biosUrl);biosUrl=null}const link=$('#download');if(link){link.removeAttribute('href');link.setAttribute('aria-disabled','true');link.textContent='BIOSをダウンロード'}const resultLaps=$('#result-laps');if(resultLaps)resultLaps.replaceChildren()}
function offerBios(image,crc){if(biosOffered)return;ofdmWorker?.postMessage({type:'disarm'});clearBios();biosOffered=true;const link=$('#download');biosUrl=URL.createObjectURL(new Blob([image],{type:'application/octet-stream'}));link.href=biosUrl;link.setAttribute('aria-disabled','false');link.textContent=`BIOSをダウンロード（512 KiB / CRC32 ${crc.toString(16).toUpperCase().padStart(8,'0')}）`;clearInterval(timer);showGoalAfterArrival()}
function markCells(fromKiB,toKiB,cls){const cells=blockCells();for(let i=fromKiB;i<toKiB&&i<cells.length;i++){const cell=cells[i],sector=grid.querySelector(`.course-sector[data-block="${i}"]`),c=cell.classList;c.remove('missing','receiving','complete','error');c.add(cls);if(sector){sector.classList.remove('missing','receiving','fec-recovering','complete','error');sector.classList.add(cls)}if(cls!=='receiving'){c.remove('fec-recovering');cell.style.removeProperty('--fill')}}}
function setBlockProgress(sequence,done,total){const cell=blockCells()[sequence];if(!cell)return;markCells(sequence,sequence+1,'receiving');cell.style.setProperty('--fill',`${Math.max(0,Math.min(100,done*100/Math.max(1,total)))}%`)}
function crashOnPacket(message){const cells=blockCells(),totalPackets=Math.max(1,Math.ceil((message.total||wireStoredSize||1)/(16*280))*22),index=Math.min(cells.length-1,Math.floor((message.index||0)*cells.length/totalPackets)),cell=cells[Math.max(0,index)];if(cell){markCells(index,index+1,'error');cell.classList.add('crash');cell.setAttribute('aria-label',`ブロック ${index+1} クラッシュ CRCエラー`)}abortTransfer(`OFDMパケットCRC不一致 #${message.index}`)}
function setFecRecovering(sequence,active,heavy=false){const cell=blockCells()[sequence],sector=grid.querySelector(`.course-sector[data-block="${sequence}"]`);if(!cell)return;const repeated=active&&cell.classList.contains('fec-recovering');cell.classList.toggle('fec-recovering',active);cell.classList.toggle('fec-heavy',active&&(heavy||repeated));sector?.classList.toggle('fec-recovering',active)}
function setWireCursor(sequence){const cells=blockCells();for(const cell of cells)cell.classList.remove('cursor');if(sequence!=null&&sequence<cells.length)cells[sequence].classList.add('cursor')}
function validateContainer(buffer,partial){const data=new Uint8Array(buffer),view=new DataView(buffer);if(data.length<28||view.getUint32(0,true)!==0x58533150)return {ok:false,error:'SXヘッダ不正'};const blocks=view.getUint16(22,true),blockSize=view.getUint16(20,true),n=grid.children.length,completeWire=new Set(),badWire=new Set();let at=view.getUint16(6,true),seen=0,truncated=false;for(let index=0;index<blocks;index++){if(at+16>data.length||at+16+view.getUint16(at+6,true)>data.length){truncated=true;break}const origSize=view.getUint16(at+4,true),stored=view.getUint16(at+6,true),expected=view.getUint32(at+12,true);at+=16;const okBlk=crc32(data.subarray(at,at+stored))===expected,k0=Math.floor(index*blockSize/wireBlockBytes),k1=Math.ceil((index*blockSize+origSize)/wireBlockBytes);markCells(k0,k1,okBlk?'complete':'error');for(let wireIndex=k0;wireIndex<k1&&wireIndex<n;wireIndex++){if(okBlk&&!badWire.has(wireIndex))completeWire.add(wireIndex);else{badWire.add(wireIndex);completeWire.delete(wireIndex)}}seen++;at+=stored}const completeBlocks=completeWire.size,badBlocks=badWire.size;recordBlockLaps(completeBlocks);setPct(`${Math.min(100,Math.round(completeBlocks*100/Math.max(1,n)))}%`);$('#summary').textContent=`完了 ${completeBlocks} / エラー ${badBlocks} / 未受信 ${Math.max(0,n-completeBlocks-badBlocks)} blocks`;if(truncated&&!partial)return {ok:false,blocks,complete:completeBlocks,bad:badBlocks,error:`Block ${seen} 未受信`};return {ok:badBlocks===0&&seen===blocks,blocks,complete:completeBlocks,bad:badBlocks,error:badBlocks?`${badBlocks} block CRC`:undefined}}
function handleOfdm(message){
  if(transferAborted||receiveFinished)return;
  if(message.type==='ofdm-wasm'){write(message.ok?'OFDM decoder: WASM':`?OFDM WASM unavailable (${message.error}) - JS fallback`);return}
  if(message.type==='ofdm-threads'){const el=$('#threads');if(el)el.textContent=`MAIN ${message.main} / WORKER ${message.workers} / FEC ${message.fec}`;return}
  if(message.type==='ofdm-restart'){resetHud();clearBios();buildGrid(wireBlockBytes,wireTotalBlocks||negotiatedBlocks);startRace(0,'OFDM packet #0 fallback');$('#ofdm-state').textContent='新送信を再同期';$('#state').textContent='OFDM packet #0 再捕捉';write(`OFDM STREAM RESTART — PACKET #${message.index} ACQUIRED`);return}
  /* Keep the legacy V3 parser gated behind its FSK block header. */
  if(wireV3&&!wireHeader)return;
  if(message.type==='ofdm-armed'){$('#decode-badge').textContent='SEARCH';$('#ofdm-sync').textContent='SEARCHING';$('#ofdm-state').textContent='同期検索中';write(`OFDM carrier search... [${message.engine||'js'}]`);return}
  if(message.type==='ofdm-carrier'){ofdmPhase=true;setStar('ofdm');$('#decode-badge').textContent='CARRIER';$('#ofdm-sync').textContent=`${message.frequency} Hz CARRIER`;$('#ofdm-correlation').textContent=message.coherence.toFixed(3);$('#ofdm-state').textContent='キャリア検出';write(`OFDM CARRIER ${message.frequency} Hz`);return}
  if(message.type==='ofdm-sync'){ofdmPhase=true;setStar('ofdm');$('#decode-badge').textContent='LOCK';$('#ofdm-sync').textContent=`LOCK #${message.index}`;$('#ofdm-correlation').textContent=message.correlation.toFixed(3);$('#ofdm-state').textContent='復調中';if((message.index&31)===0)write(`OFDM LOCK #${message.index} C=${message.correlation.toFixed(3)}`);return}
  if(message.type==='ofdm-symbol'){$('#ofdm-symbol').textContent=`${message.symbol} / 4`;return}
  if(message.type==='ofdm-search'){$('#ofdm-sync').textContent=`SEARCH ${message.samples} smp`;$('#ofdm-correlation').textContent=message.best.toFixed(3);$('#ofdm-quality').textContent=`PCM ${db(message.rms).toFixed(1)} dBFS / PK ${db(message.peak).toFixed(1)}`;$('#ofdm-drops').textContent=message.drops;return}
  if(message.type==='ofdm-packet'&&!message.valid){packetCrcErrors++;crcNgRun++;const cells=blockCells(),totalPackets=Math.max(1,Math.ceil((message.total||wireStoredSize||1)/(16*280))*22),index=Math.min(cells.length-1,Math.floor((message.index||0)*cells.length/totalPackets));moveCourseCar((message.index||0)+1,totalPackets,false);$('#course-car')?.classList.add('crc-spin');if(index>=0)setFecRecovering(index,true);$('#ofdm-state').textContent=`FEC訂正待ち CRC NG ×${crcNgRun}`;if(crcNgRun===1||(crcNgRun&15)===0)write(`OFDM PKT ${message.index} CRC NG — FEC RECOVERY PENDING${crcNgRun>1?` (${crcNgRun} consecutive)`:''}`);return}
  if(message.type==='ofdm-packet'&&message.valid&&!started)startRace(0,'first valid OFDM packet fallback');
  if(message.type==='ofdm-packet'&&message.valid&&message.total&&wireStoredSize!==message.total){wireStoredSize=message.total;wireTotalBlocks=Math.ceil(wireStoredSize/wireBlockBytes);buildGrid(wireBlockBytes,wireTotalBlocks);setCourseCarRunning();$('#payload-info').textContent=`${wireStoredSize} bytes / ${wireTotalBlocks} blocks`;$('#block-header').textContent=`OFDM STREAM V6: ${wireStoredSize.toLocaleString('ja-JP')} bytes`}
  if(message.type==='ofdm-packet'&&message.valid&&message.offset!==0xffffffff&&message.total){wireStoredSize=message.total;wireTotalBlocks=Math.ceil(wireStoredSize/wireBlockBytes);const cells=blockCells(),block=Math.min(cells.length-1,Math.floor(message.offset/wireBlockBytes)),within=(message.offset%wireBlockBytes)+(message.size||280),totalPackets=Math.ceil(message.total/(16*280))*22;setBlockProgress(block,within,Math.min(wireBlockBytes,message.total-block*wireBlockBytes));moveCourseCar(message.index+1,totalPackets);if(!receivedDataOffsets.has(message.offset)){receivedDataOffsets.add(message.offset);receivedDataBytes+=message.size||280}const elapsed=started?(performance.now()-started)/1000:0;effectiveBps=elapsed>0?receivedDataBytes*8/elapsed:0;updateHud()}
  if(message.type==='ofdm-packet'){const totalPackets=Math.ceil(message.total/(16*280))*22,diag=`C=${message.score.toFixed(3)} SNR=${message.snr.toFixed(1)} EVM=${(message.evm*100).toFixed(1)}% T=${message.timing.toFixed(2)} SWAP=${message.swap?'Y':'N'}`;$('#course-car')?.classList.remove('crc-spin');$('#ofdm-packets').textContent=`${message.crcOk} / ${totalPackets}`;$('#ofdm-correlation').textContent=message.score.toFixed(3);$('#ofdm-cfo').textContent=`${message.cfo.toFixed(1)} Hz / ${message.phase.toFixed(2)} rad`;$('#ofdm-quality').textContent=`${message.snr.toFixed(1)} dB / ${(message.evm*100).toFixed(1)}%`;$('#ofdm-crc').textContent=`${message.crcOk} OK / ${message.crcBad} NG`;$('#ofdm-drops').textContent=message.drops;$('#ofdm-recovered').textContent=`${receivedDataBytes} / ${message.total} bytes`;setPct(`${Math.min(100,Math.floor(receivedDataBytes*100/message.total))}%`);setStar('ofdm');if(crcNgRun){write(`OFDM CRC LOCK RECOVERED #${message.index} AFTER ${crcNgRun} NG`);crcNgRun=0}else if((message.index&31)===0)write(`OFDM PKT ${message.index} G${message.group} S${message.shard} CRC OK ${diag}`);return}
  if(message.type==='ofdm-fec'){fecRecovered+=message.recovered||0;if(wireHeader)setFecRecovering(wireHeader.index,false);$('#ofdm-fec').textContent=`16+6 / G${message.group} ${message.recovered}枚訂正 W${message.worker??0}`;$('#ofdm-state').textContent='エラー訂正完了';write(`OFDM FEC W${message.worker??0}: group ${message.group} — ${message.recovered} shard(s) recovered from ${message.parity} parity`);return}
  if(message.type==='ofdm-fec-failed'){fecFailures++;const cells=blockCells(),index=Math.min(cells.length-1,Math.floor(message.group*16*280/wireBlockBytes)),cell=cells[Math.max(0,index)],car=$('#course-car');if(cell){setFecRecovering(index,false);markCells(index,index+1,'error');cell.setAttribute('aria-label',`ブロック ${index+1} FEC訂正不能`)}car?.classList.add('crash');$('#ofdm-fec').textContent=`16+6 / 訂正不能 G${message.group}`;$('#ofdm-state').textContent='エラー訂正不能';abortTransfer(`FEC訂正不能 G${message.group}`);write(`?OFDM FEC RECOVERY FAILED G${message.group} MISSING ${message.missing} PARITY ${message.parity} — RECEIVER STOPPED`);return}
  if(message.type==='ofdm-partial'){if(!wireV3)validateContainer(message.data,true);return}
  if(message.type==='ofdm-complete'&&wireV3&&wireHeader){const now=performance.now();if(ofdmPhaseAt){ofdmMs+=now-ofdmPhaseAt;ofdmPhaseAt=0}fskPhaseAt=now;const block=new Uint8Array(message.data),computed=crc32(block),ok=message.valid&&block.length===wireBlockBytes&&computed===wireHeader.crc,index=wireHeader.index,sequence=wireHeader.sequence;if(ok){wireBlocks.set(index,block.slice());const blockElapsed=started?(performance.now()-started)/1000:receiveElapsed;effectiveBps=blockElapsed>0?wireBlocks.size*wireBlockBytes*8/blockElapsed:0;if(index===0&&block.length>=28){const view=new DataView(block.buffer,block.byteOffset,block.byteLength);if(view.getUint32(0,true)===0x58533150){const headerSize=view.getUint16(6,true),storedPayloadSize=view.getUint32(12,true);if(headerSize>=28&&headerSize<=block.length){wireStoredSize=headerSize+storedPayloadSize;const containerBlocks=Math.ceil(wireStoredSize/wireBlockBytes);if(containerBlocks!==wireTotalBlocks)write(`?CONTAINER SIZE ${wireStoredSize} bytes REQUIRES ${containerBlocks} blocks / NEGOTIATED ${wireTotalBlocks}`)}}}markCells(index,index+1,'complete');write(`V${wireHeader.version} BLOCK/SEQ ${sequence} CRC32 OK ${computed.toString(16).toUpperCase().padStart(8,'0')}`)}else{crcNg++;blockCrcErrors++;markCells(index,index+1,'error');write(`?V${wireHeader.version} BLOCK/SEQ ${sequence} CRC32 ERROR ${computed.toString(16).toUpperCase().padStart(8,'0')} / ${wireHeader.crc.toString(16).toUpperCase().padStart(8,'0')}`)}hudDone=wireBlocks.size;hudTotal=wireTotalBlocks||0;updateHud();$('#summary').textContent=`完了 ${wireBlocks.size} / エラー ${crcNg} / 未受信 ${wireTotalBlocks?Math.max(0,wireTotalBlocks-wireBlocks.size):'?'}`;$('#ofdm-recovered').textContent=`${wireBlocks.size*wireBlockBytes} bytes`;ofdmWorker?.postMessage({type:'disarm'});setWireCursor(null);wireHeader=null;ofdmPhase=false;if(!fskBoundary)node?.port.postMessage({type:'fsk-reset'});if(wireTotalBlocks&&wireBlocks.size===wireTotalBlocks)finishWireV3();return}
  if(message.type==='ofdm-complete'){const result=validateContainer(message.data);if(!(message.valid&&result.ok)&&!result.error)result.error=message.valid?'未完了':'Image CRC';$('#ofdm-rate').textContent=`${message.rate.toFixed(1)} kbps`;$('#ofdm-recovered').textContent=`${message.total} bytes`;$('#ofdm-fec').textContent='16+6 / GROUP COMPLETE';$('#ofdm-crc').textContent=message.valid?'IMAGE CRC OK':'IMAGE CRC ERROR';$('#decode-badge').textContent=message.valid&&result.ok?'COMPLETE':'ERROR';$('#ofdm-state').textContent=message.valid&&result.ok?'受信完了':'CRCエラー';write(message.valid&&result.ok?`LOAD COMPLETE ${message.total} bytes CRC32 ${message.crc.toString(16).toUpperCase().padStart(8,'0')}`:`?LOAD ERROR ${result.error}`);
    if(message.valid&&result.ok){receiveElapsed=started?(performance.now()-started)/1000:0;ofdmMs=receiveElapsed*1000;effectiveBps=receiveElapsed>0?message.total*8/receiveElapsed:0;hudDone=wireTotalBlocks;hudTotal=wireTotalBlocks;receiveFinished=true;updateHud();showTransferStats();const bios=reconstructBios(message.data);if(bios.ok){offerBios(bios.image,bios.crc);setStar('ok');$('#state').textContent='BIOS受信完了';write(`BIOS ${bios.image.length} bytes  CRC32 ${bios.crc.toString(16).toUpperCase().padStart(8,'0')}  READY TO SAVE`)}else{setStar('err');$('#state').textContent='BIOS再構成エラー';write(`?BIOS REBUILD ERROR ${bios.error}`);hudError()}}else{setStar('err');$('#state').textContent='OFDM受信エラー';hudError()}}
}
function handle(message){
  if(transferAborted){if(message.type==='level')queueLevel(message);return}
  if(message.type==='pcm'){if(ofdmWorker)ofdmWorker.postMessage(message,[message.left,message.right]);return}
  if(message.type==='start-count'){showStartCutin(message.value);return}
  if(message.type==='start-signal'){startRace(message.agoMs||0,'triangle start signal');return}
  if(message.type==='fsk-bits'){rawBits=(rawBits+message.bits).slice(-32);const nibs=rawBits.match(/.{1,4}/g)||[];const bin=nibs.join(' ');const hex=(nibs.filter(n=>n.length===4).map(n=>parseInt(n,2).toString(16).toUpperCase()).join('').match(/.{1,2}/g)||[]).join(' ');let asc='';for(let i=0;i+8<=rawBits.length;i+=8){const c=parseInt(rawBits.substr(i,8),2);asc+=(c>=32&&c<127)?String.fromCharCode(c):'·'}$('#fsk-bits').textContent=`${bin}\n${hex}  "${asc}"`;$('#fsk-bit-count').textContent=`${message.count} bits`;if($('#fsk-status').textContent!=='完了')fskStat('デコード中','#6ee9ff');return}
  if(message.type==='level'){
    queueLevel(message);return;
  }
  if(message.type==='fsk-lock'){const scoreMax=message.scoreMax||64;if(wireHeader){write(`FSK CANDIDATE IGNORED DURING OFDM BLOCK ${wireHeader.sequence}`);return}ofdmWorker?.postMessage({type:'disarm'});wireV3=true;ofdmPhase=false;setStar('fsk-on');fskStat('同期','#50d8ff');$('#state').textContent='FSK同期';$('#ofdm-state').textContent='FSK受信中';$('#decode-badge').textContent='FSK WAIT';$('#sync-quality').textContent=`${message.score}/${scoreMax} (${Math.round(message.score*100/scoreMax)}%)`;write(`Found PS1SX FSK (${message.baud||'?'} baud / ${message.rate} Hz / ${message.symbolSamples} samples / offset ${message.offset})`);return }
  if(message.type==='fsk-input-channel')return;
  if(message.type==='fsk-negotiation'){const now=performance.now();negotiationMs=started?now-started:0;fskPhaseAt=now;if(message.protocol<3||!Number.isInteger(message.blockBytes)||message.blockBytes<1024||message.blockBytes>131072||(message.blockBytes&(message.blockBytes-1))!==0||!Number.isInteger(message.blocks)||message.blocks<1||message.blocks>1024){write(`?UNSUPPORTED NEGOTIATION ${message.text}`);hudError();return}wireBlockBytes=message.blockBytes;negotiatedBlocks=message.blocks;wireTotalBlocks=negotiatedBlocks;freshNegotiation=true;buildGrid(wireBlockBytes,negotiatedBlocks);wireBlocks=new Map();wireStoredSize=0;crcNg=0;resetReception(false,true);$('#header-progress').textContent=`NEG ${message.text.length} bytes`;$('#payload-info').textContent=`${message.blockBytes} bytes × ${message.blocks} blocks`;$('#ofdm-fec').textContent=`${message.dataShards}+${message.parityShards} / NEGOTIATED`;$('#state').textContent=`PS1SX V${message.protocol} NEGOTIATED`;write(`NEGOTIATE ${message.text}`);return}
  if(message.type==='fsk-header-sum-retry'){if(wireHeader)return;fskSumErrors++;showBlockHeader({...message,headerAttempt:message.attempt},false);fskStat('ヘッダSUMエラー','#ff6680');$('#header-crc').textContent=`SUM ERROR ${message.sum.toString(16).toUpperCase().padStart(2,'0')}`;write(`?V${message.version} FSK HEADER SUM ERROR — RECEIVE ABORTED`);abortTransfer('FSKブロックヘッダSUMエラーで受信終了');return}
  if(message.type==='fsk-header-sum-error'){if(wireHeader)return;fskSumErrors++;showBlockHeader(message,false);fskStat('ヘッダSUMエラー','#ff6680');$('#header-crc').textContent=`SUM ERROR ${message.sum.toString(16).toUpperCase().padStart(2,'0')}`;write(`?V${message.version} FSK HEADER SUM ERROR ${message.bytes.map(v=>v.toString(16).toUpperCase().padStart(2,'0')).join(' ')} — RECEIVE ABORTED`);abortTransfer('FSKブロックヘッダSUMエラーで受信終了');return}
  if(message.type==='fsk-header-version-error'){if(wireHeader)return;const version=message.version.toString(16).toUpperCase().padStart(2,'0');fskStat('ヘッダVERエラー','#ff6680');$('#header-crc').textContent=`VERSION ERROR ${version}`;$('#state').textContent='FSKブロックヘッダVERエラー';write(`?FSK HEADER VERSION ERROR ${message.bytes.map(v=>v.toString(16).toUpperCase().padStart(2,'0')).join(' ')}`);return}
  if(message.type==='fsk-block'){const now=performance.now();if(message.mono||message.swap){$('#state').textContent='非対応: STEREO以外の送信';fskStat('MODEエラー','#ff6680');write('?BURST MODE ERROR — STEREO REQUIRED');return}if(fskPhaseAt){fskMs+=now-fskPhaseAt;fskPhaseAt=0}ofdmPhaseAt=now;const version=message.version||3,isOneBased=version>=5,index=isOneBased?message.sequence-1:message.sequence,firstSequence=isOneBased?1:0;if(index<0||index>=negotiatedBlocks){showSequenceError(message);fskStat('SEQエラー','#ff6680');$('#header-crc').textContent='SEQ ERROR';$('#state').textContent=`不正なSEQ ${String(message.sequence).padStart(3,'0')}`;write(`?V${version} FSK SEQ ${message.sequence} ERROR — VALID ${firstSequence}..${isOneBased?negotiatedBlocks:negotiatedBlocks-1}`);return}if(wireHeader&&message.sequence!==wireHeader.sequence+1){write(`?V${version} FSK BLOCK/SEQ ${message.sequence} REJECTED — EXPECTED ${wireHeader.sequence+1}`);return}showBlockHeader(message,true);if(wireHeader&&wireHeader.sequence!==message.sequence){setFecRecovering(wireHeader.index,false);markCells(wireHeader.index,wireHeader.index+1,'error');write(`?BLOCK/SEQ ${wireHeader.sequence} INCOMPLETE — FEC FINALIZE TIMEOUT`)}fskBoundary=false;wireV3=true;if(message.sequence===firstSequence&&!freshNegotiation&&wireBlocks.size===0){resetReception(false);wireStoredSize=0;wireTotalBlocks=negotiatedBlocks;crcNg=0}freshNegotiation=false;wireHeader={version,sequence:message.sequence,index,mono:false,crc:message.crc>>>0};setWireCursor(index);setBlockProgress(index,0,Math.ceil(wireBlockBytes/2304)*20);ofdmPhase=false;fskStat(`BLOCK/SEQ ${message.sequence}`,'#3fe0a0');$('#header-crc').textContent=`${message.crc.toString(16).toUpperCase().padStart(8,'0')}`;$('#state').textContent=`BLOCK/SEQ ${message.sequence} OFDM待機`;write(`V${version} FSK BLOCK/SEQ ${message.sequence} STEREO CRC32 ${message.crc.toString(16).toUpperCase().padStart(8,'0')} H${message.headerAttempt||1}`);ofdmWorker?.postMessage({type:'arm',index:0,block:message.sequence,mode:'stereo'});return}
  if(message.type==='fsk-line'){if(message.line){fskLines++;fskChars+=message.line.length+2;$('#header-progress').textContent=`${fskLines}行 / ${fskChars}文字`;write(message.line)}return}
  if(message.type==='fsk-framing-error'){if(wireHeader)return;fskStat('再同期','#f8d548');write(`?FRAMING ERROR #${message.count||1} bit=${message.bit||'?'} baud=${message.baud||'?'} — RESYNC`);return}
  if(message.type==='fsk-header'){
    if(message.valid){wireV3=false;resetReception();fskStat('完了','#3fe0a0');$('#state').textContent='ヘッダ受信完了';$('#header-crc').textContent=`OK ${message.crc}`;$('#payload-info').textContent=`${message.fields.STORED||'?'} / ${message.fields.SIZE||'?'} bytes`;$('#ofdm-state').textContent='同期検索中';$('#detail').textContent=`${message.fields.NAME||'PS1BIOS'} / ${message.fields.SIZE||'?'} bytes / CRC32 ${message.fields.CRC32||'?'}`;write(`HEADER CRC OK (${message.crc})`);write('Loading...');}
    else{fskStat('CRCエラー','#ff6680');$('#state').textContent='ヘッダCRCエラー';$('#header-crc').textContent=`ERROR ${message.crc}`;write(`?HEADER CRC ERROR (${message.crc})`)}
  }
}
async function start(){
  await stop(true);const id=$('#device').value;
  stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:id?{exact:id}:undefined,channelCount:{ideal:2},sampleRate:{ideal:48000},echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});
  const openedTrack=stream.getAudioTracks()[0]; if(openedTrack?.label)localStorage.setItem(DEVICE_LABEL_KEY,openedTrack.label);
  await devices();const track=stream.getAudioTracks()[0],settings=track.getSettings();if(settings.channelCount===1){const error=new Error('モノラル入力のため受信できません');error.code='MONO_INPUT';error.sampleRate=settings.sampleRate;throw error}context=new AudioContext({sampleRate:44100});ofdmWorker=new Worker('ofdm-worker.js?v=51');ofdmWorker.onmessage=event=>handleOfdm(event.data);ofdmWorker.onerror=event=>{write(`?OFDM WORKER ERROR ${event.message}`);$('#decode-badge').textContent='WORKER ERROR'};await context.audioWorklet.addModule('decoder-worker.js?v=41');node=new AudioWorkletNode(context,'sx-input');const pcmChannel=new MessageChannel();ofdmWorker.postMessage({type:'connect-pcm'},[pcmChannel.port1]);node.port.postMessage({type:'connect-ofdm'},[pcmChannel.port2]);applyAnalyzerSetting();inputGainNode=context.createGain();applyInputGain();context.createMediaStreamSource(stream).connect(inputGainNode).connect(node);node.connect(context.destination);node.port.onmessage=event=>handle(event.data);$('#context-info').textContent=`${context.sampleRate} Hz / ${(context.baseLatency*1000).toFixed(1)} ms`;$('#processing').textContent=`AGC ${settings.autoGainControl?'ON':'OFF'} / NS ${settings.noiseSuppression?'ON':'OFF'} / EC ${settings.echoCancellation?'ON':'OFF'}`;
  applyAnalyzerSetting();loading=true;started=0;ofdmPhase=false;resetTransferStats();wireHeader=null;wireV3=false;wireBlocks=new Map();wireStoredSize=0;wireTotalBlocks=negotiatedBlocks;guideAt=0;guidePeak=0;hold.l=hold.r=-60;clearBios();setStar('');buildGrid(wireBlockBytes,negotiatedBlocks);node.port.postMessage({type:'start-detector-reset'});$('#elapsed').textContent='0.00 s';$('#signal-progress').textContent='スタート信号待機';$('#sync-quality').textContent='未同期';$('#payload-info').textContent='未確定';$('#ofdm-state').textContent='スタート待機';$('#decode-badge').textContent='READY';$('#block-header').textContent='OFDM STREAM V6: START待機';$('#level-guide').textContent='ぴー、ぴー、ぷーーー 待ち';ofdmWorker.postMessage({type:'arm',index:0,mode:'stereo'});timer=setInterval(()=>{if(started){$('#elapsed').textContent=`${((performance.now()-started)/1000).toFixed(2)} s`;updateHud()}},50);$('#activity').setAttribute('aria-hidden','false');$('#hud').setAttribute('aria-hidden','false');setPct('0%');resetHud();$('#state').textContent='スタート信号待機';$('#format').textContent=`${settings.channelCount||'?'} ch / ${settings.sampleRate||context.sampleRate} Hz`;$('#detail').textContent='';setToggle(true);if(navigator.wakeLock)try{wake=await navigator.wakeLock.request('screen')}catch{}write('BURST V6 — waiting for triangle start signal');
}
async function stop(keepToggle){loading=false;started=0;ofdmPhase=false;pendingLevel=null;if(levelFrame){cancelAnimationFrame(levelFrame);levelFrame=0}setWireCursor(null);clearBios();setStar('');setCourseCarIdle();$('#activity').setAttribute('aria-hidden','true');$('#hud').setAttribute('aria-hidden','true');setPct('0%');resetHud();clearInterval(timer);if(node){node.disconnect();node=null}if(inputGainNode){inputGainNode.disconnect();inputGainNode=null}if(ofdmWorker){ofdmWorker.terminate();ofdmWorker=null}if(context){await context.close();context=null}if(stream){stream.getTracks().forEach(track=>track.stop());stream=null}if(wake){await wake.release();wake=null}for(const channel of ['l','r']){$(`#meter-${channel}`).style.width='0';$(`#meter-${channel}`).classList.remove('clip');$(`#db-${channel}`).textContent='-∞'}$('#level').textContent='-∞ dBFS';$('#level-guide').textContent='信号待ち';$('#level-guide').style.color='';$('#context-info').textContent='未接続';$('#state').textContent='停止中';$('#elapsed').textContent='0.00 s';if(!keepToggle)setToggle(false)}
function resetFromButton(){resetTransferStats();wireHeader=null;wireBlocks=new Map();wireStoredSize=0;wireTotalBlocks=negotiatedBlocks;wireV3=false;ofdmPhase=false;crcNg=0;started=0;clearBios();setWireCursor(null);setStar('');buildGrid(wireBlockBytes,negotiatedBlocks);resetHud();node?.port.postMessage({type:'start-detector-reset'});ofdmWorker?.postMessage({type:'arm',index:0,mode:'stereo'});$('#elapsed').textContent='0.00 s';$('#signal-progress').textContent='スタート信号待機';$('#sync-quality').textContent='未同期';$('#payload-info').textContent='未確定';$('#ofdm-state').textContent='スタート待機';$('#ofdm-packets').textContent='0 / ?';$('#ofdm-crc').textContent='0 OK / 0 NG';$('#ofdm-recovered').textContent='0 bytes';$('#ofdm-drops').textContent='0';$('#decode-badge').textContent=stream?'READY':'IDLE';$('#block-header').textContent='OFDM STREAM V6: START待機';$('#state').textContent=stream?'スタート信号待機':'停止中';write('RESET — waiting for triangle start signal')}
let toggling=false;
$('#toggle').onclick=async()=>{
  if(toggling)return;toggling=true;
  const b=$('#toggle');b.classList.remove('attract');b.disabled=true;b.textContent=stream?'停止中…':'開始中…';
  try{if(stream)await stop();else await start()}
  catch(error){write(`ERROR ${error.message}`);await stop().catch(()=>{});if(error.code==='MONO_INPUT'){$('#state').textContent=t('monoError');$('#format').textContent=`1 ch / ${error.sampleRate||'?'} Hz`;$('#detail').textContent=t('monoHelp')}else $('#state').textContent=t('inputError')}
  finally{b.disabled=false;toggling=false;setToggle(!!stream)}
};
$('#reset').onclick=resetFromButton;$('#close-complete').onclick=()=>$('#complete-dialog').close();
const analyzerSaved=localStorage.getItem('ps1sx.analyzer');if(analyzerSaved!==null)$('#analyzer-enabled').checked=analyzerSaved==='1';$('#analyzer-enabled').onchange=applyAnalyzerSetting;applyAnalyzerSetting();
const gainSaved=Number(localStorage.getItem('ps1sx.inputGainDb'));if(Number.isFinite(gainSaved))$('#input-gain').value=String(Math.max(-12,Math.min(18,gainSaved)));$('#input-gain').oninput=applyInputGain;applyInputGain();
$('#device').onchange=()=>{const selected=$('#device').selectedOptions[0];if(selected?.value)localStorage.setItem(DEVICE_LABEL_KEY,selected.textContent);else localStorage.removeItem(DEVICE_LABEL_KEY);if(stream&&!toggling)start().catch(error=>write(`ERROR ${error.message}`))};navigator.mediaDevices?.addEventListener('devicechange',devices);devices().catch(()=>{});
document.addEventListener('sx-locale-change',()=>{setToggle(!!stream);devices().catch(()=>{});if(!stream){$('#state').textContent=t('stopped');$('#format').textContent=t('disconnected')}else if(!started)$('#state').textContent=t('startWait');updateHud()});
write('READY.');
fetch('ofdm-decoder.wasm?v=11').then(r=>r.ok?r.arrayBuffer():Promise.reject('HTTP '+r.status)).then(b=>WebAssembly.instantiate(b,{})).then(()=>write('OFDM DECODER: WASM')).catch(e=>write(`OFDM DECODER: JS FALLBACK (${e})`));
