(()=>{
const messages={
ja:{tagline:'実機PlayStationから180秒以内のBIOS音声転送を目指します。',what:'これは何？',intro:'所有する初代PlayStationの512 KiB BIOSを、アナログ音声出力から180秒以内にブラウザへ転送することを目標とした高速実験版です。受信・復調・誤り検出／訂正・BIOS再構成はブラウザ内で完結し、BIOSデータをサーバーへ送信しません。',warning:'現在は開発中です。エミュレータ起動と合成信号の成功は、物理PlayStationからの完全回収を保証しません。実機達成まではUNVERIFIEDとして扱います。',stereoOnly:'注意：ステレオ音声入力専用です。モノラル入力では受信できません。',cdImage:'CD起動イメージ（CUE + BIN ZIP）をダウンロード',start:'音声入力を開始',stop:'停止',reset:'受信リセット',input:'入力',defaultInput:'既定の音声入力',state:'状態',disconnected:'未接続',stopped:'停止中',receiveTime:'受信時間',estimate:'推定所要時間',level:'レベル',blocks:'受信ブロック',missing:'未受信',receiving:'受信中',correcting:'訂正中',complete:'完了',crcError:'CRCエラー',waiting:'待機',signalWait:'信号待ち',gain:'レベル補正',scopeHelp:'音声入力を開始してください。連続ステレオOFDMを専用Workerで復調します。',analysisOn:'解析ON',analysisHelp:'OFDM音声のリアルタイム推定値',snr:'推定SNR',bandPeak:'OFDM帯域ピーク',highLow:'高域 / 低域',balance:'L/Rバランス',peaks:'ピーク L / R',rms:'RMS L / R',crest:'クレスト L / R',stereoCorrelation:'ステレオ相関',clips:'クリップ',processing:'音声補正',threads:'スレッド',sync:'同期',packets:'パケット',symbol:'シンボル',correlation:'相関',phase:'CFO / 位相',modulation:'変調',restore:'復元',rate:'実効速度',drops:'ドロップ',log:'受信ログ',verified:'512 KiB BIOSを正常に復元しました。',download:'BIOSをダウンロード',result:'RACE RESULT',laps:'LAP RESULTS',close:'閉じる',language:'言語',startWait:'スタート信号待機',inputError:'入力エラー',monoError:'エラー: モノラル入力',monoHelp:'この入力デバイスは1チャンネルです。ステレオ入力デバイスを選択してください。',goSearch:'GO! OFDM同期検索中',effective:'実効',summary:(done,error,missing)=>`完了 ${done} / エラー ${error} / 未受信 ${missing} blocks`},audioInput:n=>`音声入力 ${n}`},
en:{tagline:'Aiming to transfer a real PlayStation BIOS over audio in under 180 seconds.',what:'What is this?',intro:'This experimental high-speed edition transfers the 512 KiB BIOS from an original PlayStation you own to a browser through its analog audio output, targeting under 180 seconds. Capture, demodulation, error detection/correction, and BIOS reconstruction all run in the browser; BIOS data is never sent to a server.',warning:'This project is under development. Emulator and synthetic-signal success do not prove full recovery from physical hardware. Physical completion remains UNVERIFIED.',stereoOnly:'Caution: stereo audio input is required. Mono input cannot receive this signal.',cdImage:'Download CD boot image (CUE + BIN ZIP)',start:'Start audio input',stop:'Stop',reset:'Reset reception',input:'Input',defaultInput:'Default audio input',state:'Status',disconnected:'Disconnected',stopped:'Stopped',receiveTime:'Receive time',estimate:'Estimated duration',level:'Level',blocks:'Received blocks',missing:'Missing',receiving:'Receiving',correcting:'Correcting',complete:'Complete',crcError:'CRC error',waiting:'Waiting',signalWait:'Waiting for signal',gain:'Input gain',scopeHelp:'Start audio input. Continuous stereo OFDM is demodulated in a dedicated Worker.',analysisOn:'Analysis ON',analysisHelp:'Real-time estimates for the OFDM audio signal',snr:'Estimated SNR',bandPeak:'OFDM band peak',highLow:'High / low band',balance:'L/R balance',peaks:'Peak L / R',rms:'RMS L / R',crest:'Crest L / R',stereoCorrelation:'Stereo correlation',clips:'Clipping',processing:'Audio processing',threads:'Threads',sync:'Sync',packets:'Packets',symbol:'Symbol',correlation:'Correlation',phase:'CFO / phase',modulation:'Modulation',restore:'Recovered',rate:'Effective rate',drops:'Drops',log:'Receiver log',verified:'The 512 KiB BIOS was reconstructed successfully.',download:'Download BIOS',result:'RACE RESULT',laps:'LAP RESULTS',close:'Close',language:'Language',startWait:'Waiting for start signal',inputError:'Input error',monoError:'Error: mono input',monoHelp:'This capture device exposes one channel. Select a stereo input device.',goSearch:'GO! Searching for OFDM sync',effective:'Effective',summary:(done,error,missing)=>`Complete ${done} / Errors ${error} / Missing ${missing} blocks`,audioInput:n=>`Audio input ${n}`},
'zh-CN':{tagline:'目标是在180秒内通过音频传输真实PlayStation的BIOS。',what:'这是什么？',intro:'这是一个高速实验版，目标是在180秒内，通过您拥有的初代PlayStation模拟音频输出，将512 KiB BIOS传输到浏览器。接收、解调、检错/纠错和BIOS重建全部在浏览器内完成；BIOS数据不会发送到服务器。',warning:'本项目仍在开发中。模拟器和合成信号测试成功，并不代表已从真实主机完整恢复。真实硬件验证完成前均标记为UNVERIFIED。',stereoOnly:'注意：仅支持立体声音频输入，单声道输入无法接收。',cdImage:'下载CD启动镜像（CUE + BIN ZIP）',start:'开始音频输入',stop:'停止',reset:'重置接收',input:'输入',defaultInput:'默认音频输入',state:'状态',disconnected:'未连接',stopped:'已停止',receiveTime:'接收时间',estimate:'预计用时',level:'电平',blocks:'接收区块',missing:'未接收',receiving:'接收中',correcting:'纠错中',complete:'完成',crcError:'CRC错误',waiting:'等待中',signalWait:'等待信号',gain:'输入增益',scopeHelp:'请开始音频输入。连续立体声OFDM由专用Worker解调。',analysisOn:'分析开启',analysisHelp:'OFDM音频信号实时估计',snr:'估计SNR',bandPeak:'OFDM频带峰值',highLow:'高频 / 低频',balance:'L/R平衡',peaks:'峰值 L / R',rms:'RMS L / R',crest:'峰均比 L / R',stereoCorrelation:'立体声相关性',clips:'削波',processing:'音频处理',threads:'线程',sync:'同步',packets:'数据包',symbol:'符号',correlation:'相关性',phase:'CFO / 相位',modulation:'调制',restore:'已恢复',rate:'有效速率',drops:'丢包',log:'接收日志',verified:'已成功重建512 KiB BIOS。',download:'下载BIOS',result:'比赛结果',laps:'单圈结果',close:'关闭',language:'语言',startWait:'等待起步信号',inputError:'输入错误',monoError:'错误：单声道输入',monoHelp:'此采集设备只有一个声道。请选择立体声输入设备。',goSearch:'GO! 正在搜索OFDM同步',effective:'有效',summary:(done,error,missing)=>`完成 ${done} / 错误 ${error} / 未接收 ${missing} blocks`,audioInput:n=>`音频输入 ${n}`}
};
const normalize=value=>value?.toLowerCase().startsWith('zh')?'zh-CN':value?.toLowerCase().startsWith('en')?'en':'ja';
let locale=normalize(localStorage.getItem('ps1sx.locale')||navigator.languages?.[0]||navigator.language);
const t=(key,...args)=>{const value=messages[locale]?.[key]??messages.ja[key]??key;return typeof value==='function'?value(...args):value};
function apply(){document.documentElement.lang=locale;for(const node of document.querySelectorAll('[data-i18n]'))node.textContent=t(node.dataset.i18n);for(const node of document.querySelectorAll('[data-i18n-aria]'))node.setAttribute('aria-label',t(node.dataset.i18nAria));const select=document.querySelector('#locale');if(select)select.value=locale;document.dispatchEvent(new CustomEvent('sx-locale-change',{detail:{locale}}))}
function setLocale(value){locale=normalize(value);localStorage.setItem('ps1sx.locale',locale);apply()}
window.sxI18n={t,setLocale,get locale(){return locale},apply};
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#locale')?.addEventListener('change',event=>setLocale(event.target.value));apply()});
})();
